# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(170, 40, 113, 21))
        self.input_name.setObjectName("input_name")
        self.input_name2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name2.setGeometry(QtCore.QRect(170, 90, 113, 21))
        self.input_name2.setObjectName("input_name2")
        self.label_name2 = QtWidgets.QLabel(self.centralwidget)
        self.label_name2.setGeometry(QtCore.QRect(50, 40, 111, 16))
        self.label_name2.setObjectName("label_name2")
        self.label_name3 = QtWidgets.QLabel(self.centralwidget)
        self.label_name3.setGeometry(QtCore.QRect(50, 90, 101, 16))
        self.label_name3.setObjectName("label_name3")
        self.label_name4 = QtWidgets.QLabel(self.centralwidget)
        self.label_name4.setGeometry(QtCore.QRect(50, 140, 60, 16))
        self.label_name4.setObjectName("label_name4")
        self.input_name3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name3.setGeometry(QtCore.QRect(170, 140, 113, 21))
        self.input_name3.setObjectName("input_name3")
        self.button_name2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_name2.setGeometry(QtCore.QRect(300, 340, 113, 32))
        self.button_name2.setObjectName("button_name2")
        self.label_name5 = QtWidgets.QLabel(self.centralwidget)
        self.label_name5.setGeometry(QtCore.QRect(50, 190, 60, 16))
        self.label_name5.setObjectName("label_name5")
        self.label_name6 = QtWidgets.QLabel(self.centralwidget)
        self.label_name6.setGeometry(QtCore.QRect(50, 240, 60, 16))
        self.label_name6.setObjectName("label_name6")
        self.label_name7 = QtWidgets.QLabel(self.centralwidget)
        self.label_name7.setGeometry(QtCore.QRect(50, 290, 60, 16))
        self.label_name7.setObjectName("label_name7")
        self.input_name4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name4.setGeometry(QtCore.QRect(170, 190, 113, 21))
        self.input_name4.setObjectName("input_name4")
        self.input_name5 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name5.setGeometry(QtCore.QRect(170, 240, 113, 21))
        self.input_name5.setObjectName("input_name5")
        self.input_name6 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name6.setGeometry(QtCore.QRect(170, 290, 113, 21))
        self.input_name6.setObjectName("input_name6")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(320, 0, 101, 16))
        self.label_name.setObjectName("label_name")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 20, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.button_name = QtWidgets.QPushButton(self.centralwidget)
        self.button_name.setGeometry(QtCore.QRect(150, 340, 113, 32))
        self.button_name.setObjectName("button_name")
        self.button_name3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_name3.setGeometry(QtCore.QRect(450, 340, 113, 32))
        self.button_name3.setObjectName("button_name3")
        self.label_name8 = QtWidgets.QLabel(self.centralwidget)
        self.label_name8.setGeometry(QtCore.QRect(50, 420, 71, 16))
        self.label_name8.setObjectName("label_name8")
        self.input_name7 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name7.setGeometry(QtCore.QRect(170, 420, 113, 21))
        self.input_name7.setObjectName("input_name7")
        self.label_name9 = QtWidgets.QLabel(self.centralwidget)
        self.label_name9.setGeometry(QtCore.QRect(400, 420, 271, 20))
        self.label_name9.setText("")
        self.label_name9.setObjectName("label_name9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 1"))
        self.label_name2.setText(_translate("MainWindow", "Student name:"))
        self.label_name3.setText(_translate("MainWindow", "No of attempts:"))
        self.label_name4.setText(_translate("MainWindow", "Score 1:"))
        self.button_name2.setText(_translate("MainWindow", "SAVE"))
        self.label_name5.setText(_translate("MainWindow", "Score 2:"))
        self.label_name6.setText(_translate("MainWindow", "Score 3:"))
        self.label_name7.setText(_translate("MainWindow", "Score 4:"))
        self.label_name.setText(_translate("MainWindow", "Grade Manager"))
        self.button_name.setText(_translate("MainWindow", "SUBMIT"))
        self.button_name3.setText(_translate("MainWindow", "CLEAR"))
        self.label_name8.setText(_translate("MainWindow", "Final score:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
